### ISSUE TITLE
TypeError with ElasticsearchFilterBackend in DEFAULT_FILTER_BACKENDS

### ISSUE THREAD

**Issue by chrisforrette** [liberation/django-elasticsearch#18]
Hello!

I've been trying to work this into a project and running into an error when I put `ElasticsearchFilterBackend` into the Django REST framework `DEFAULT_FILTER_BACKENDS` setting.

My config looks like this:

```python
REST_FRAMEWORK = {
    # ...
    'DEFAULT_FILTER_BACKENDS': (
        'rest_framework.filters.OrderingFilter',
        'django_elasticsearch.contrib.restframework.ElasticsearchFilterBackend'
    ),
    # ...
}
```

And when I try to search an endpoint, I get a `TypeError`: `get_ordering() takes exactly 4 arguments (2 given)` on line 43 of `django_elasticsearch/contrib/restframework.py` (`ordering = self.get_ordering(request)`).

Looking at the source, it looks like the method call should have `queryset` and `view` arguments passed to it as well, but simply adding those in doesn't fix the problem.

**Comment by lauxley** [comment]
Hi,
the module is not yet compatible with restframework >3 since its API changed quite a lot, see #11.
