### ISSUE TITLE
No way to serialize abstract methods

### ISSUE THREAD

**Issue by Tuss4** [liberation/django-elasticsearch#20]
According to [this](https://github.com/liberation/django-elasticsearch/blob/master/django_elasticsearch/serializers.py#L109), when it encounters a method_name it can't find on the instance it just goes `pass`. Based on the example in test_app I assumed that there was a way to serialize `@property` abstract methods on the class.

**Comment by lauxley** [comment]
Hi,
yeah this code is messy but if you look closely if it's not a model field, it will continue with ```return getattr(instance, field_name)``` and raise an AttributeError if it does not exists. Also keep in mind the field needs to be described in the elasticsearch mapping anyway.

**Comment by Tuss4** [comment]
Yeah, I ended up using a combination of elasticsearch-py and a DRF serializer to get the job done.
