### ISSUE TITLE
Documentation - Getting Started

### ISSUE THREAD

**Issue by ghiotion** [liberation/django-elasticsearch#23]
I'm very keen to use this, but I'm not making it very far.  Elastic search is running on 9200, I suppose I should begin by stating that.  `curl -GET "http://localhost:9200/"`
    {
      "status" : 200,
      "name" : "Erg",
      "cluster_name" : "elasticsearch",
      "version" : {
        "number" : "1.7.1",
        "build_hash" : "b88f43fc40b0bcd7f173a1f9ee2e97816de80b19",
        "build_timestamp" : "2015-07-29T09:54:16Z",
        "build_snapshot" : false,
        "lucene_version" : "4.10.4"
      },
      "tagline" : "You Know, for Search"
    }

Attached this to a very simple model

    class Document(EsIndexable, models.Model):
         user = models.ForeignKey(User)
        docfile = models.FileField(upload_to='documents/%Y/%m/%d')
        tags = models.ManyToManyField(Tag)
        posted_date = models.DateTimeField()

then in shell: 
    >>> from home.models import Document
    >>> Document.es.create_index()
    >>> Document.es.search('value')
        []
    >>> Document.es.count()
    0

I've got several rows of data in the model but nothing is coming up when I search.  Any thoughts?

Django version 1.8.4

**Comment by lauxley** [comment]
Hi, as stated in the documentation:
```django-elasticsearch DOES NOT index documents by itself unless told to, either set settings.ELASTICSEARCH_AUTO_INDEX to True to index your models when you save them, or call directly myinstance.es.do_index().````

To index already existing Documents, you can call ``Document.es.reindex_all()``.

Hope it helps
