### ISSUE TITLE
Auto Indexing on Already saved data

### ISSUE THREAD

**Issue by Dean-Christian-Armada** [liberation/django-elasticsearch#52]
There are instances where you will use this library on the later parts of development..

In my case,, I just used this library and every data that is already saved before I install this package is not indexed..

By setting **ELASTICSEARCH_AUTO_INDEX** to true,, everything that will be saved will contain an index.. This will enable me to set index to every data that is already saved by updating or resaving it which is done manually or a lot easier approach is by re-saving them via for loop

But is there an easier way? or something easier can be done to do that? like a manage.py command or something?

**Comment by lauxley** [comment]
You can call 

``` python
MyModel.es.create_index()
MyModel.es.index_all()
```

or

```
MyModel.es.flush()
```

which deletes the index before reindexing everything.

**Comment by Dean-Christian-Armada** [comment]
Oh ok Thanks!
