### ISSUE TITLE
Filter Contains

### ISSUE THREAD

**Issue by ghost** [liberation/django-elasticsearch#63]
Filter contains didn't work,,,

```python
>>> ModelBuah.es.get(id=3)
{u'nama': u'Langsat', u'jml': 50}
>>> ModelBuah.es.filter(nama__contains='sat')
[]
>>> ModelBuah.es.queryset.filter(nama__contains='sat')
[]
```

**Comment by lauxley** [comment]
It depends how you tokenize the 'nama' field.

**Comment by ghost** [comment]
What do you mean? Can you point to part of manual about tokenize?

**Comment by lauxley** [comment]
[partial word tokenizer](https://www.elastic.co/guide/en/elasticsearch/reference/current/analysis-tokenizers.html#_partial_word_tokenizers)
