### ISSUE TITLE
Unable to get repr for <class 'django_elasticsearch.query.EsQueryset'>

### ISSUE THREAD

**Issue by mugbya** [liberation/django-elasticsearch#76]
hi， I wrote test code  

model
```py

from django_elasticsearch.models import EsIndexable

class UserInfoSE(EsIndexable, models.Model):
    tel = models.CharField(max_length=50, null=True, unique=False, default='')

```

view
```py
UserInfoSE.es.queryset.all()

```
and settings:

```
ELASTICSEARCH_URL = 'http://192.168.99.101:9200'
```

but I got some error: Unable to get repr for <class 'django_elasticsearch.query.EsQueryset'>

**Comment by lauxley** [comment]
That's weird and probably shouldn't be this way but it's not the documented way to call `.all()`, try `UserInfoSE.es.all()`.
